#version 450

layout(location = 0) in vec2 vUV;
layout(location = 0) out vec4 outColor;

// Texture sampler - receives the texture generated by compute shader
layout(binding = 0) uniform sampler2D computedTexture;

void main() {
    // Sample the texture that was generated by the compute shader
    vec3 color = texture(computedTexture, vUV).rgb;
    outColor = vec4(color, 1.0);
}
